# Results for Climate Change Competition

The results are in! After only four weeks of working on this problem area, Columbia University students were able to dramatically improve prediction of satellite images that can help us to monitor deforestation, an important contributor to climate change.

Submitted models spanned the full menu of classic ML, deep learning, and ensemble approaches. Click the below link to navigate to the Model Playground for this competition or scroll down to see details about various models that were submitted to the competition as well as who won prizes and medals for their submissions:

https://www.modelshare.org/detail/model:1535

**Congrats to all winners and all who participated!**

**Scroll down to see how we calculated competitions winners and to find details about winners/winning approaches!**

# Import Libraries and Data

In [ ]:
%%capture
!pip install aimodelshare-nightly

In [ ]:
import aimodelshare as ai
from aimodelshare import Competition
from aimodelshare.aws import set_credentials

import pandas as pd
pd.set_option('display.max_columns', 500)

In [ ]:
set_credentials()

AI Modelshare Username:··········
AI Modelshare Password:··········
AI Model Share login credentials set successfully.

In [ ]:
mycompetition = Competition(playground_url="https://srdmat3yhf.execute-api.us-east-1.amazonaws.com/prod/m")

In [ ]:
data = pd.read_csv("model_eval_data_mastertable_private.csv", sep="\t")

# Clean Submission Data

### Remove Post-deadline Submissions

In [ ]:
# check latest submission
data.timestamp.max()

'2022-04-08 02:37:17.008089'

No submissions after deadline (11:59:59 on Wednesday April 8th, 2022)

### Remove Invalid Submissions

In [ ]:
# in case of duplicate models keep only the first submission
cols_dedup = data.loc[:,"accuracy":"unitnormalization_layers"].columns
data = data.sort_values("timestamp").drop_duplicates(subset=cols_dedup, keep="first")

In [ ]:
# enforce 5 models/day rule 
data['date'] = pd.to_datetime(data['timestamp']).dt.date
data = data.sort_values("timestamp").groupby(['username', 'date']).head(5)

After removing duplicate submissions and submissions in violation of the 5 models/day rule, we have 380 valid submissions.

### View Final Leaderboard

In [ ]:
mycompetition.stylize_leaderboard(data.sort_values("f1_score", ascending=False).head())

# Who won 1st, 2nd, and 3rd place for cash prizes?

### Get Usernames Associated with Highest Ranking Submissions

In [ ]:
result=data.groupby("username")[["f1_score"]].max()
result.sort_values("f1_score", ascending=False).head(3)

             f1_score
username
SuperbTUM    0.797511
prajwalseth  0.795735
hywang       0.795430

## **The winners are Mingzhe Hu from the Fu Foundation Graduate Program in Electrical Engineering, Prajwal Seth from the Quantitative Methods in the Social Sciences program in the Graduate School of Arts and Sciences, and Huiying Wang from the Statistics program in the Graduate School of Arts and Sciences!** 

Leaderboard usernames: SuperbTUM, prajwalseth, and hywang. 

#Congratulations!  

Here are some interesting details about the models submitted by our winners...

### Model Architecture of #1

Our first place model winner, Mingzhe Hu, extensively used Convolution layers (Over 50!) with Batch Normalization to generate a powerful prediction model.

In [ ]:
mod1 = mycompetition.compare_models([188], naming_convention="keras")
mycompetition.stylize_compare(mod1)

### Model Architecture of #2
Our second place submission, by Prajwal Seth, partially used transfer learning.  Prajwal stacked a large Resnet archicture on top of four fully connected layers to predict forests satellite bands.  Prajwal also experimented with using various types of bands beyond our exampe approach to preprocessing (which only used RGB bands).

In [ ]:
mod2 = mycompetition.compare_models([252], naming_convention="keras")
mycompetition.stylize_compare(mod2)

### Model Architecture of #3
Our third place submission, by Huiying Wang, also made use of a large Resnet architecture stacked on top of a smaller fully connected neural network architecture with two layers.  The major difference here is that Global Average Pooling was used to output data from the final Resnet layer output rather than flattening the data out into a single vector.

In [ ]:
mod3 = mycompetition.compare_models([287], naming_convention="keras")
mycompetition.stylize_compare(mod3)

Congrats again to our 1st, second, and third place winners above.  Now let's see, which participants won Gold, Silver, or Bronze medals...

# Medal Winners by Gold (top 1%), Silver (top 5%), and Bronze (top 15%) Leaderboard Performance Percentiles

### Calculate Leaderboard Percentiles

In [ ]:
import numpy as np
# Remove models by 1st, 2nd, and 3rd place winners first.
df = data
#define values
values = ["SuperbTUM", "prajwalseth","hywang"]

#drop rows that contain any value in the list
df = df[df.username.isin(values) == False]

a = df['f1_score']

p15 = np.percentile(a, 85)
p5 = np.percentile(a, 95)
p1 = np.percentile(a, 99)
p1, p5, p10

(0.7559308390900767, 0.7236059109461075, 0.6806382018213584)

### Top 15th percentile of model submissions Bronze Medal Winner(s)!

In [ ]:
data_medals = df.sort_values("f1_score", ascending=False).groupby("username").head(1)

In [ ]:
bronzewinners=data_medals[(data_medals['f1_score'] >= p15) & (data_medals['f1_score'] <= p5)]['username'].unique()
str(bronzewinners)

"['JoeyDuodu' 'cjc2279' 'cindyl' 'timwu' 'jc5492' 'CompeteForFun'\n 'sharlene0113']"

## Our bronze medal winners are:

Name  | Username(s) | Columbia Program |
-------------------|------------------|------------------
Joseph Duodu       | JoeyDuodu | Computer Science 
Cindy Jia-Yi Chen      | cjc2279 | Quant. Methods Soc. Sciences
Cindy Xinyue Li      | cindyl | Quant. Methods Soc. Sciences
Guangyu Wu      | timwu | Computer Science 
Jian Tong Chua     | jc5492 | Quant. Methods Soc. Sciences 
Yanlin Zhang       | CompeteForFun | Quantitative Methods in the Social Sciences
Sharlene Chen     | sharlene0113 | Industrial Engineering & Operations Research


Congratulations!

Bronze medalists made submissions using several kinds of deep learning architectures including Inception architectures, Resnet variations, varied approaches with stacked Convolution layers, and more!  They used both Pytorch and Tensorflow Keras to build and fit their models.

In [ ]:
# Here are examples of models submitted by our bronze medal winners:
import pandas as pd
pd.options.mode.chained_assignment = None
bronze_example_data=data_medals[(data_medals['f1_score'] >= p15) & (data_medals['f1_score'] <= p5)]
mycompetition.stylize_leaderboard(bronze_example_data)

### Top 5th percentile of model submissions Silver Medal Winners!

In [ ]:

silverwinners=data_medals[(data_medals['f1_score'] >= p5) & (data_medals['f1_score'] <= p1)]['username'].unique()

silverwinners

array(['anhvu', 'Panati', 'Alan'], dtype=object)

## Our silver medal winners are:

Name  | Username(s) | Columbia Program |
-------------------|------------------|------------------
Anh-Vu Nguyen       | anhvu | Data Science
Pruthvi Reddy Panati     | Panati | Quant. Methods Soc. Sciences
Alan Luo       | Alan | Computer Science

Silver medalists made submissions made use of deep learning architectures including such as stacked Convolution layers, deep repeated convolution layers with regularization, and transfer learning! They used both Pytorch and Tensorflow Keras to build and fit their models.

Congratulations!

In [ ]:
# Here are examples of models submitted by our silver medal winners:
silverexample_data=data_medals[(data_medals['f1_score'] >= p5) & (data_medals['f1_score'] <= p1)]

mycompetition.stylize_leaderboard(silverexample_data)

In [ ]:
silvermedalists = mycompetition.compare_models([389,341,16], naming_convention="keras")
mycompetition.stylize_compare(silvermedalists)

### Top 1 percentile of model submissions Gold Medal Winners!

In [ ]:
goldwinners=data_medals[(data_medals['f1_score'] >= p1) ]['username'].unique()
goldwinners

array(['AustinZ', 'NMilinkovich', 'vkalmath'], dtype=object)

## Our gold medal winners are:

Name  | Username(s) | Columbia Program |
-------------------|------------------|------------------
Kechengjie Zhu       | AustinZ | Computer Science
Nicholas Paul Milinkovich   | NMilinkovich | Quant. Methods Soc. Sciences
Vijay Shivalingayya Kalmath      | vkalmath| Computer Science

Gold medalists made submissions made use of deep learning architectures including such as stacked Convolution layers, deep repeated convolution layers with regularization, and transfer learning! They used both Pytorch and Tensorflow Keras to build and fit their models.

Congratulations!

In [ ]:
# Here are examples of models submitted by our gold medal winners:
goldexample_data=data_medals[(data_medals['f1_score'] >= p1)]
mycompetition.stylize_leaderboard(goldexample_data)

In [ ]:
goldmedalists = mycompetition.compare_models([414,284,315], naming_convention="keras")
mycompetition.stylize_compare(goldmedalists)


# Medals for Model Improvement Throughout Competition

In [ ]:
data[data['f1_score'] >= .85]

Empty DataFrame
Columns: [accuracy, f1_score, precision, recall, mse, rmse, mae, r2, ml_framework, transfer_learning, deep_learning, model_type, depth, num_params, globalmaxpooling2d_layers, unfold_layers, attention_layers, permute_layers, convolution2d_layers, linear_layers, additiveattention_layers, globalmaxpool2d_layers, maxpool3d_layers, maxpooling3d_layers, transformerdecoderlayer_layers, maxunpool2d_layers, crossmaplrn2d_layers, dropout2d_layers, inputlayer_layers, bilinear_layers, minimum_layers, factory_kwargs_layers, maxunpool3d_layers, separableconvolution2d_layers, spatialdropout2d_layers, dropout_layers, separableconv1d_layers, rnnbase_layers, separableconv2d_layers, zeropad2d_layers, avgpool3d_layers, lppool1d_layers, globalaveragepooling2d_layers, maxpooling1d_layers, constantpad2d_layers, upsampling3d_layers, avgpool2d_layers, averagepooling2d_layers, instancenorm2d_layers, lazybatchnorm3d_layers, syncbatchnorm_layers, fractionalmaxpool3d_layers, lazyconv1d_layers, avgpool1d_layers, averagepooling3d_layers, batchnorm1d_layers, lazyconvtranspose1d_layers, channelshuffle_layers, textvectorization_layers, embedding_layers, abstractrnncell_layers, maximum_layers, simplernncell_layers, uninitializedparameter_layers, gaussiannoise_layers, lazylinear_layers, randomrotation_layers, lazybatchnorm1d_layers, discretization_layers, bidirectional_layers, randomwidth_layers, repeatvector_layers, fractionalmaxpool2d_layers, instancenorm1d_layers, resizing_layers, zeropadding1d_layers, module_layers, sequential_layers, transformerencoderlayer_layers, randomcontrast_layers, dense_layers, batchnorm2d_layers, stringlookup_layers, convtranspose1d_layers, subtract_layers, randomflip_layers, globalmaxpool3d_layers, multiply_layers, convlstm1d_layers, instancenorm3d_layers, adaptiveavgpool3d_layers, zeropadding3d_layers, globalaveragepooling1d_layers, maxpool2d_layers, convtranspose2d_layers, masking_layers, timedistributed_layers, adaptivemaxpool1d_layers, maxunpool1d_layers, locallyconnected1d_layers, ...]
Index: []

None of the models reached the performance threshold of f1>0.85. Therefore no medals were awarded for model improvements over and above the threshold.