<p align="center"><img width="50%" src="https://aimodelsharecontent.s3.amazonaws.com/aimodshare_banner.jpg" /></p>


---

<p align="center"><h1 align="center">Social Mobility Competition Model Submission Guide - Predictions Only (No Model Metadata Extraction) </h1>

---
Let's share our models to a centralized leaderboard, so that we can collaborate and learn from the model experimentation process...

**Instructions:**
1.   Get data in and set up X_train / X_test / y_train
2.   Preprocess data
3. Fit model on preprocessed data
4. Generate predictions from X_test data and submit to competition
5. Repeat submission process to improve place on leaderboard

## 1. Get data in and set up X_train, X_test, y_train objects

In [ ]:
#install aimodelshare library
! pip install aimodelshare --upgrade

In [2]:
# Get competition data
from aimodelshare import download_data
download_data('public.ecr.aws/y2e2a1d6/social_mobility_competition_data-repository:latest')

Downloading [===========================================>     ]

Data downloaded successfully.

In [3]:
# Separate data into X_train, y_train, and X_test
import pandas as pd

X_train = pd.read_csv("/content/social_mobility_competition_data/X_train.csv")
y_train = pd.read_csv("/content/social_mobility_competition_data/y_train.csv", squeeze=True)

X_test=pd.read_csv("/content/social_mobility_competition_data/X_test.csv")

X_train.head()

,geoid,place,pop,housing,P_1,P_2,P_3,P_4,P_5,P_6,...,P_112,P_113,P_114,P_115,P_116,P_117,P_118,P_119,P_120,P_121
0,1003.0,Baldwin County,187114,104061,82.847946,98.593450,101.77671,82.477325,62.60906,65.417640,...,0.0,19.10,0.00,2.01,0.00,3.52,0.0,0.00,0.0,0.0
1,1005.0,Barbour County,27321,11829,76.313896,93.878720,90.70294,91.192700,101.84381,102.085240,...,0.0,45.16,0.00,4.84,0.00,1.61,0.0,3.23,0.0,0.0
2,1007.0,Bibb County,22754,8981,73.765620,104.868470,82.12955,68.382010,71.17644,69.621730,...,0.0,30.91,0.00,7.27,0.00,1.82,0.0,0.00,0.0,0.0
3,1013.0,Butler County,20624,9964,92.096670,121.073296,117.82320,143.117360,131.00436,134.067840,...,0.0,41.07,0.00,5.36,0.00,1.79,0.0,0.00,0.0,0.0
4,1015.0,Calhoun County,117714,53289,76.938210,95.478250,98.32662,87.650314,64.08210,60.688488,...,0.0,18.79,0.61,3.03,0.61,2.42,0.0,0.00,0.0,0.0

In [4]:
# Check Data Shape
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)

(1259, 125)
(1259, 125)
(1259,)

##2.   Preprocess data

In [ ]:
# Write and execute code to preprocess data here

##3. Fit model on preprocessed data

In [ ]:
# Write and execute code to fit model on preprocessed data here.

In [5]:
#Set credentials using modelshare.org username/password

from aimodelshare.aws import set_credentials
    
apiurl="https://89lu7cpgh1.execute-api.us-east-1.amazonaws.com/prod/m"
#This is the unique rest api that powers this Playground -- make sure to update the apiurl for new competition deployments

set_credentials(apiurl=apiurl)

AI Modelshare Username:··········
AI Modelshare Password:··········
AI Model Share login credentials set successfully.

In [6]:
#Instantiate Competition
import aimodelshare as ai
mycompetition= ai.Competition(apiurl)

## **4. Submit Model predictions to leaderboard (without extracting model architecture information):**
- model metadata extraction allows you use compare_models() and instantiate_model() functions.

In [7]:
#Generate a list of predictions between .2 and .6
import numpy as np
predicted_values = np.random.uniform(.2, .6, size=len(X_test))
predicted_values = predicted_values.tolist()

In [8]:
#Submit Model predictions to leaderboard (without extracting model architecture information): 

# Submit to Competition Leaderboard
mycompetition.submit_model(model_filepath = None,
                                 preprocessor_filepath=None,
                                 prediction_submission=predicted_values)

Insert search tags to help users find your model (optional):
Provide any useful notes about your model (optional):

Your model has been submitted as model version 8

To submit code used to create this model or to view current leaderboard navigate to Model Playground:

 https://www.modelshare.org/detail/model:2821

In [9]:
# Get leaderboard to explore current best model architectures

# Get raw data in pandas data frame
data = mycompetition.get_leaderboard()

# Stylize leaderboard data
mycompetition.stylize_leaderboard(data)

You can also compare two or more models for any models submitted to the leaderboard using example code for model metadata extraction (see code tab for this competition at www.modelshare.org for submission examples.)
```
data=mycompetition.compare_models([1,2], verbose=1)
mycompetition.stylize_compare(data)
```

#####  (Optional Extension) Submit Model With Custom Metadata: 
Can use to add team names or any other missing data you may wish to share on the leaderboard

In [ ]:
# Custom metadata can be added by passing a dict to the custom_metadata argument of the submit_model() method
# This option can be used to fill in missing data points or add new columns to the leaderboard

custom_meta = {'team': 'team one',
               'model_type': 'your_model_type',
               'new_column': 'new metadata'}

mycompetition.submit_model(model_filepath = None,
                                 preprocessor_filepath=None,
                                 prediction_submission=predicted_values,
                                 custom_metadata = custom_meta)